apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job-one
  labels:
    co.courselabs.k8sfun: jobs
    app: pi-one
    dp: '50'    
spec:
  template:
    spec:
      containers:
        - name: pi
          image: kiamol/ch05-pi
          command: ["dotnet", "Pi.Web.dll", "-m", "console", "-dp", "50"]
      restartPolicy: Never
