# CronJob using current stable API
# In older clusters, this would have been batch/v1beta1
apiVersion: batch/v1
kind: CronJob
metadata:
  name: legacy-cleanup
  labels:
    kubernetes.courselabs.co: api-versions
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cleanup
              image: busybox:1.28
              command:
                - /bin/sh
                - -c
                - echo "Running cleanup task"
          restartPolicy: OnFailure
