apiVersion: v1
kind: Pod
metadata:
  name: app-with-logging
  namespace: logging-app
  labels:
    app: logging
    type: multi-container
spec:
  containers:
  - name: app
    image: busybox:1.36
    command:
    - sh
    - -c
    - "while true; do echo $(date) - Application log message >> /var/log/app.log; sleep 5; done"
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
    envFrom:
    - secretRef:
        name: db-credentials
  - name: log-processor
    image: busybox:1.36
    command:
    - sh
    - -c
    - "tail -f /var/log/app.log | grep 'Application'"
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  volumes:
  - name: log-volume
    emptyDir: {}
