apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: widgetario
    co.courselabs.k8sfun: hackathon
spec:
  selector:
    matchLabels:
        app: widgetario
        component: web
  template:
    metadata:
      labels: 
        app: widgetario
        component: web
        hackathon: part-1
    spec:
      containers:
        - name: app
          image: widgetario/web:21.03
          ports:
            - containerPort: 80
              name: http