apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-headless
  labels:
    app: {{ .Release.Name }}-postgres
    kubernetes.courselabs.co: troubleshooting-3
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP