apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: products-db
  labels:
    app: widgetario
spec:
  selector:
    matchLabels:
      app: products-db
  serviceName: products-db
  replicas: 2
  template:
    metadata:
      labels:
        app: products-db
    spec:      
      automountServiceAccountToken: false
      containers:
        - name: app
          image: widgetario/products-db:postgres-replicated
          envFrom:
            - secretRef:
                name: products-db-password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data  
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: widgetario
    spec:
      accessModes: 
       - ReadWriteOnce
      resources:
        requests:
          storage: 50Mi