apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  template:
    spec:
      containers:
        - name: whoami
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
