{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingress-access
  labels:
    app: {{ .Release.Name }}
    kubernetes.courselabs.co: troubleshooting-3
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: {{ .Values.ingress.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
{{- end }}