apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-svc
  labels:
    app: {{ .Release.Name }}-web
    kubernetes.courselabs.co: troubleshooting-3
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-web