apiVersion: v1
kind: Pod
metadata:
  name: container-security-demo
  labels:
    kubernetes.courselabs.co: security
spec:
  containers:
    - name: sec-ctx-demo
      image: busybox:1.28
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        runAsUser: 2000
        runAsGroup: 3000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
