apiVersion: v1
kind: Pod
metadata:
  name: fsgroup-demo
  labels:
    kubernetes.courselabs.co: security
spec:
  securityContext:
    fsGroup: 2000
    runAsUser: 1000
    runAsGroup: 3000
  containers:
    - name: fsgroup-container
      image: busybox:1.28
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: data-volume
          mountPath: /data
  volumes:
    - name: data-volume
      emptyDir: {}
