apiVersion: v1
kind: Pod
metadata:
  name: non-root-demo
  labels:
    kubernetes.courselabs.co: security
spec:
  containers:
    - name: non-root-container
      image: busybox:1.28
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
