apiVersion: v1
kind: Pod
metadata:
  name: pod-security-demo
  labels:
    kubernetes.courselabs.co: security
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: sec-ctx-demo
      image: busybox:1.28
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data/demo
  volumes:
    - name: sec-ctx-vol
      emptyDir: {}
