apiVersion: v1
kind: Pod
metadata:
  name: readonly-demo
  labels:
    kubernetes.courselabs.co: security
spec:
  containers:
    - name: readonly-container
      image: busybox:1.28
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        readOnlyRootFilesystem: true
        runAsUser: 1000
      volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
  volumes:
    - name: tmp-volume
      emptyDir: {}
