apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: troubleshooting-2
  labels:
    kubernetes.courselabs.co: troubleshooting-2
data:
  app.conf: |
    debug=false
    environment=production
    api_endpoint=https://api.example.com
    cache_timeout=300