apiVersion: v1
kind: Service
metadata:
  name: troubleshooting-app
  namespace: troubleshooting-2
  labels:
    kubernetes.courselabs.co: troubleshooting-2
spec:
  selector:
    app: web-app
    kubernetes.courselabs.co: troubleshooting-2
  ports:
  - port: 8040
    targetPort: 80
    nodePort: 30040
  type: LoadBalancer