web:
  replicaCount: 2
  image:
    repository: kiamol/ch02-whoami
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80

database:
  replicaCount: 3
  image:
    repository: postgres
    tag: 14-alpine
  password: postgres123
  storage: 1Gi

ingress:
  enabled: true
  host: whoami.local
  port: 30030