apiVersion: v1
kind: Namespace
metadata:
  name: secure-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: secure-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: secure-app
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: secure-app
subjects:
- kind: ServiceAccount
  name: app-sa
  namespace: secure-app
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: secure-app
type: Opaque
stringData:
  API_KEY: abc123xyz789
  API_SECRET: super-secret-value
---
apiVersion: v1
kind: Pod
metadata:
  name: secure-app
  namespace: secure-app
  labels:
    app: secure-app
spec:
  serviceAccountName: app-sa
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: app
    image: busybox:1.36
    command:
    - sh
    - -c
    - "while true; do echo 'Running...'; sleep 30; done"
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: api-credentials
